apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: metaphor-envs
spec:
  backendType: vault
  # todo look at mount point
  vaultMountPoint: kubernetes/kubefirst
  vaultRole: external-secrets
  kvVersion: 2
  data:
    - name: secret-one
      key: secret/data/preprod/metaphor
      property: SECRET_ONE
    - name: secret-two
      key: secret/data/preprod/metaphor
      property: SECRET_TWO
