kind: Service
apiVersion: v1
metadata:
  name: metaphor
  labels:
    run: metaphor
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
  selector:
    run: metaphor
  externalTrafficPolicy: Cluster
  type: NodePort
