apiVersion: apps/v1
kind: Deployment
metadata:
  name: metaphor
spec:
  replicas: 2
  selector:
    matchLabels:
      run: metaphor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: metaphor
    spec:
      serviceAccount: metaphor-sa
      containers:
        - image: 126827061464.dkr.ecr.us-east-2.amazonaws.com/metaphor:@CI_COMMIT_REF@
          name: metaphor
          env:
            - name: SECRET_ONE
              valueFrom:
                secretKeyRef:
                  key: secret-one
                  name: metaphor-envs
            - name: SECRET_TWO
              valueFrom:
                secretKeyRef:
                  key: secret-two
                  name: metaphor-envs
            - name: PACKAGE_VERSION
              value: @PACKAGE_VERSION@
            - name: DOCKER_TAG
              value: @DOCKER_TAG@
          envFrom:
          - configMapRef:
              name: metaphor-cm
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: "128Mi"
            requests:
              cpu: 40m
              memory: "64Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
            timeoutSeconds: 30
      restartPolicy: Always
